language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
sudo: false
deploy:
  provider: npm
  email: juerg.hunziker@gmail.com
  api_key:
    secure: pXo8DFRzbxbg+34Y7rOacbMGjvwUKxv6IalCaGgOSfPnjFhXMw5Egln9/do2uWuTOm8RBqAXKlnkpH6o/eXw5Rub/yLV4kt41g2v++iMnON6kJx6yGynVdY0E7nog1VyqEtwdq5NTQ3PkxASJI+r7mHNBHg8vEbg82beQYgMjlQ=
  on:
    tags: true
    all_branches: true
    node: '9'
