language: node_js
node_js:
- '0.11'
- '0.12'
- '4.0'
- '4.1'
- '5.0'
sudo: false
deploy:
  provider: npm
  email: juerg.hunziker@gmail.com
  api_key:
    secure: M4I35T8twToL0Tf+xF5F3Jvz8QUzyTlSTzoTTIN34ujGrZrRw+mob2Z9WfRDbiEQDtmkRiCU+jMrp8O+y0N35blLsxXrE6GuG5wneSA7wMkuj1pfnX0hGgb5gjBm3qdr2SMQWKwJLg6booSaI4mth3hMqzAn0TI6P+RbOAxlX74=
  on:
    tags: true
    all_branches: true
    node: '0.12'